FPS = 60
ACTIVE_ROWS = 50
ACTIVE_AREA_HEIGHT = 800
ACTIVE_AREA_WIDTH = 400
HORIZONTAL_SPACING = 50
BETWEEN_AREAS_SPACING = 500
VERTICAL_SPACING = 7

SCREEN_SIZE = (200 + ACTIVE_AREA_WIDTH * 2 + BETWEEN_AREAS_SPACING,
    ACTIVE_AREA_HEIGHT)
WIDTH, HEIGHT = SCREEN_SIZE

NIGHT_CODES = {1: 'whiplash', 2: 'american-idiot', 3: 'psycho', 4: 'battle-without-honor-or-humanity'}