FPS = 40
ACTIVE_ROWS = 25
ACTIVE_AREA_HEIGHT = 800
ACTIVE_AREA_WIDTH = 400
HORIZONTAL_SPACING = 50
BETWEEN_AREAS_SPACING = 500
VERTICAL_SPACING = 7

SCREEN_SIZE = (200 + ACTIVE_AREA_WIDTH * 2 + BETWEEN_AREAS_SPACING,
    ACTIVE_AREA_HEIGHT)
WIDTH, HEIGHT = SCREEN_SIZE